// Code generated by MockGen. DO NOT EDIT.
// Source: ./security/dao.go

// Package security is a generated GoMock package.
package security

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSecurityDao is a mock of SecurityDao interface.
type MockSecurityDao struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityDaoMockRecorder
}

// MockSecurityDaoMockRecorder is the mock recorder for MockSecurityDao.
type MockSecurityDaoMockRecorder struct {
	mock *MockSecurityDao
}

// NewMockSecurityDao creates a new mock instance.
func NewMockSecurityDao(ctrl *gomock.Controller) *MockSecurityDao {
	mock := &MockSecurityDao{ctrl: ctrl}
	mock.recorder = &MockSecurityDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityDao) EXPECT() *MockSecurityDaoMockRecorder {
	return m.recorder
}

// GetRemoteToken mocks base method.
func (m *MockSecurityDao) GetRemoteToken(token string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteToken", token)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteToken indicates an expected call of GetRemoteToken.
func (mr *MockSecurityDaoMockRecorder) GetRemoteToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteToken", reflect.TypeOf((*MockSecurityDao)(nil).GetRemoteToken), token)
}
