mockgen -source=./internal/cart/repository.go -destination=./tests/mocks/cart_repository.go -package=mocks
mockgen -source=./internal/cart/service.go -destination=./tests/mocks/cart_service.go -package=mocks
mockgen -source=./internal/engine/db/collection.go -destination=./tests/mocks/db_collection.go -package=mocks
mockgen -source=./internal/engine/errs/rest.go -destination=./tests/mocks/errs_rest.go -package=mocks
mockgen -source=./internal/engine/errs/validation.go -destination=./tests/mocks/errs_validation.go -package=mocks
mockgen -source=./internal/engine/httpx/client.go -destination=./tests/mocks/httpx_client.go -package=mocks
mockgen -source=./internal/engine/log/logger.go -destination=./tests/mocks/log_logger.go -package=mocks
mockgen -source=./internal/rabbit/consume/consume_article_exist.go -destination=./tests/mocks/consume_article_exist.go -package=mocks
mockgen -source=./internal/rabbit/consume/consume_logout.go -destination=./tests/mocks/consume_logout.go -package=mocks
mockgen -source=./internal/rabbit/consume/consume_order_placed.go -destination=./tests/mocks/consume_order_placed.go -package=mocks
mockgen -source=./internal/rabbit/emit/rabbit_channel.go -destination=./tests/mocks/rabbit_channel.go -package=mocks
mockgen -source=./internal/rabbit/emit/rabbit_emit.go -destination=./tests/mocks/rabbit_emit.go -package=mocks
mockgen -source=./internal/security/repository.go -destination=./tests/mocks/security_repository.go -package=mocks
mockgen -source=./internal/security/service.go -destination=./tests/mocks/security_service.go -package=mocks
mockgen -source=./internal/services/service.go -destination=./tests/mocks/services_service.go -package=mocks
