basePath: /v1
definitions:
  apperr.ValidationErr:
    properties:
      messages:
        items:
          $ref: '#/definitions/apperr.errField'
        type: array
    type: object
  apperr.errField:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
  cart.AddArticleData:
    properties:
      articleId:
        maxLength: 100
        minLength: 1
        type: string
      quantity:
        maximum: 100
        minimum: 1
        type: integer
    required:
    - articleId
    - quantity
    type: object
  cart.Article:
    properties:
      articleId:
        maxLength: 100
        minLength: 1
        type: string
      quantity:
        maximum: 100
        minimum: 1
        type: integer
      valid:
        type: boolean
      validated:
        type: boolean
    required:
    - articleId
    - quantity
    type: object
  cart.Cart:
    properties:
      _id:
        type: string
      articles:
        items:
          $ref: '#/definitions/cart.Article'
        type: array
      created:
        type: string
      enabled:
        type: boolean
      orderId:
        type: string
      updated:
        type: string
      userId:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - articles
    - userId
    type: object
  cart.OrderPlacedEvent:
    properties:
      cartId:
        example: CartId
        type: string
      orderId:
        example: OrderId
        type: string
      valid:
        example: true
        type: boolean
    type: object
  cart.ValidationEvent:
    properties:
      articleId:
        example: ArticleId
        type: string
      referenceId:
        example: UserId
        type: string
      valid:
        example: true
        type: boolean
    type: object
  engine.ErrorData:
    properties:
      error:
        type: string
    type: object
  r_consume.consumeArticleDataMessage:
    properties:
      exchange:
        example: ""
        type: string
      message:
        $ref: '#/definitions/cart.ValidationEvent'
      queue:
        example: ""
        type: string
      type:
        example: article-exist
        type: string
    type: object
  r_consume.consumeOrderPlacedMessage:
    properties:
      exchange:
        example: ""
        type: string
      message:
        $ref: '#/definitions/cart.OrderPlacedEvent'
      queue:
        example: ""
        type: string
      type:
        example: order-placed
        type: string
    type: object
  r_consume.logoutMessage:
    properties:
      message:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklEIjoiNjZiNjBlYzhlMGYzYzY4OTUzMzJlOWNmIiwidXNlcklEIjoiNjZhZmQ3ZWU4YTBhYjRjZjQ0YTQ3NDcyIn0.who7upBctOpmlVmTvOgH1qFKOHKXmuQCkEjMV3qeySg
        type: string
      type:
        example: logout
        type: string
    type: object
  r_emit.ArticleValidationData:
    properties:
      articleId:
        example: ArticleId
        type: string
      referenceId:
        example: UserId
        type: string
    type: object
  r_emit.PlaceArticlesData:
    properties:
      id:
        example: ArticleId
        type: string
      quantity:
        example: 10
        type: integer
    type: object
  r_emit.PlacedData:
    properties:
      articles:
        items:
          $ref: '#/definitions/r_emit.PlaceArticlesData'
        type: array
      cartId:
        example: CartId
        type: string
      userId:
        example: UserId
        type: string
    type: object
  r_emit.SendPlacedMessage:
    type: object
  r_emit.SendValidationMessage:
    properties:
      exchange:
        example: cart
        type: string
      message:
        $ref: '#/definitions/r_emit.ArticleValidationData'
      queue:
        example: cart
        type: string
      type:
        example: article-exist
        type: string
    type: object
host: localhost:3003
info:
  contact:
    email: nmarsollier@gmail.com
    name: Nestor Marsollier
  description: Microservicio de Carrito.
  title: CartGo
  version: "1.0"
paths:
  /rabbit/article-exist:
    get:
      consumes:
      - application/json
      description: Luego de solicitar validaciones de catalogo, las validaciones las
        recibimos en esta Queue, con el mensaje type article-data.
      parameters:
      - description: Message para Type = article-exist
        in: body
        name: type
        required: true
        schema:
          $ref: '#/definitions/r_consume.consumeArticleDataMessage'
      produces:
      - application/json
      responses: {}
      summary: Mensage Rabbit order/article-exist
      tags:
      - Rabbit
  /rabbit/cart/article-exist:
    put:
      consumes:
      - application/json
      description: Solicitamos las validaciones ar articulos a catalogo. Queue y Exchange
        es donde nos reponde.
      parameters:
      - description: Mensage de validacion
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/r_emit.SendValidationMessage'
      produces:
      - application/json
      responses: {}
      summary: Emite Validar Artículos a Cart cart/article-exist
      tags:
      - Rabbit
  /rabbit/cart/place-order:
    put:
      consumes:
      - application/json
      description: Cuando se hace checkout enviamos un comando a orders para que inicie
        el proceso de la orden.
      parameters:
      - description: Place order
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/r_emit.SendPlacedMessage'
      produces:
      - application/json
      responses: {}
      summary: Emite Placed Order desde Cart
      tags:
      - Rabbit
  /rabbit/logout:
    get:
      consumes:
      - application/json
      description: Escucha de mensajes logout desde auth.
      parameters:
      - description: Estructura general del mensage
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/r_consume.logoutMessage'
      produces:
      - application/json
      responses: {}
      summary: Mensage Rabbit
      tags:
      - Rabbit
  /rabbit/order-placed:
    get:
      consumes:
      - application/json
      description: Cuando se recibe order-placed se actualiza el order id del carrito.
        No se respode a este evento.
      parameters:
      - description: Message para Type = order-placed
        in: body
        name: type
        required: true
        schema:
          $ref: '#/definitions/r_consume.consumeOrderPlacedMessage'
      produces:
      - application/json
      responses: {}
      summary: Mensage Rabbit order/order-placed
      tags:
      - Rabbit
  /v1/cart:
    get:
      consumes:
      - application/json
      description: Obtiene el carrito actual.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cart
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Obtener carrito.
      tags:
      - Cart
  /v1/cart/article:
    post:
      consumes:
      - application/json
      description: Agrega un articulo del carrito actual.
      parameters:
      - description: ID de articlo
        in: path
        name: articleId
        required: true
        type: string
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Articulo a Agregar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/cart.AddArticleData'
      produces:
      - application/json
      responses:
        "200":
          description: Cart
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Agregar Articulo
      tags:
      - Cart
  /v1/cart/article/:articleId:
    delete:
      consumes:
      - application/json
      description: Elimina un articulo del carrito actual.
      parameters:
      - description: ID de articlo
        in: path
        name: articleId
        required: true
        type: string
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Eliminar Articulo
      tags:
      - Cart
  /v1/cart/article/:articleId/decrement:
    post:
      consumes:
      - application/json
      description: Eliminar 1 al articulo actual.
      parameters:
      - description: ID de articlo
        in: path
        name: articleId
        required: true
        type: string
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cart
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Agregar 1 Articulo
      tags:
      - Cart
  /v1/cart/article/:articleId/increment:
    post:
      consumes:
      - application/json
      description: Agregar 1 al articulo actual.
      parameters:
      - description: ID de articlo
        in: path
        name: articleId
        required: true
        type: string
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cart
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Agregar 1 Articulo
      tags:
      - Cart
  /v1/cart/checkouts:
    post:
      consumes:
      - application/json
      description: Hace checkout del carrito actual
      parameters:
      - description: ID de articlo
        in: path
        name: articleId
        required: true
        type: string
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Checkout Articulo
      tags:
      - Cart
  /v1/cart/validate:
    get:
      consumes:
      - application/json
      description: Valida el carrito para checkout
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/engine.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/engine.ErrorData'
      summary: Validar Carrito
      tags:
      - Cart
swagger: "2.0"
