// Code generated by MockGen. DO NOT EDIT.
// Source: ./tools/db/connection.go

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockDBConn is a mock of DBConn interface.
type MockDBConn struct {
	ctrl     *gomock.Controller
	recorder *MockDBConnMockRecorder
}

// MockDBConnMockRecorder is the mock recorder for MockDBConn.
type MockDBConnMockRecorder struct {
	mock *MockDBConn
}

// NewMockDBConn creates a new mock instance.
func NewMockDBConn(ctrl *gomock.Controller) *MockDBConn {
	mock := &MockDBConn{ctrl: ctrl}
	mock.recorder = &MockDBConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBConn) EXPECT() *MockDBConnMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockDBConn) Exec(query string, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockDBConnMockRecorder) Exec(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBConn)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockDBConn) QueryRow(sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBConnMockRecorder) QueryRow(sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDBConn)(nil).QueryRow), varargs...)
}

// Reset mocks base method.
func (m *MockDBConn) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockDBConnMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockDBConn)(nil).Reset))
}
